spring:
  zipkin:
    #enabled: true
    enabled: false
    baseUrl: http://zipkin:9411

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
