server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${mysql:localhost}:3306/moviedb?createDatabaseIfNotExist=true
    username: root #${user:root}
    password: password #${pass:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:movie.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    username: guest
    password: guest
    host: ${rabbitmq:localhost}
    port: 5672

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Microservice
