insert into moviedb(name, genre, url_stream) values('IT', 'terror', 'what')
insert into moviedb(name, genre, url_stream) values('La masacre de texas', 'terror', 'what')
insert into moviedb(name, genre, url_stream) values('Jack el destripador', 'terror', 'what')
insert into moviedb(name, genre, url_stream) values('Anabelle', 'terror', 'what')
insert into moviedb(name, genre, url_stream) values('Fast and Furious', 'acción', 'what')
insert into moviedb(name, genre, url_stream) values('shadow', 'acción', 'what')
insert into moviedb(name, genre, url_stream) values('Orgullo y prejuicio', 'romance', 'what')
insert into moviedb(name, genre, url_stream) values('The notebook', 'romance', 'what')